pdf:
	xelatex adapt-transf
	biber adapt-transf
	xelatex adapt-transf
	xelatex adapt-transf

fix:
	texliveonfly -c xelatex adapt-transf

clean:
	rm *.bbl *.nav *.run.xml *.snm *.synctex* *.vrb *.xdv *.aux *.bcf *.blg *.fdb_latexmk *.fls *.log *.out *.toc
