pdf:
	xelatex cat-presentation
	biber cat-presentation
	xelatex cat-presentation
	xelatex cat-presentation

fix:
	texliveonfly -c xelatex cat-presentation

clean:
	rm *.bbl *.nav *.run.xml *.snm *.synctex* *.vrb *.xdv *.aux *.bcf *.blg *.fdb_latexmk *.fls *.log *.out *.toc
