pdf:
	xelatex phd-defense-presentation
	biber phd-defense-presentation
	xelatex phd-defense-presentation
	xelatex phd-defense-presentation

fix:
	sudo texliveonfly -c xelatex phd-defense-presentation

clean:
	rm *.bbl *.nav *.run.xml *.snm *.synctex* *.vrb *.xdv *.aux *.bcf *.blg *.fdb_latexmk *.fls *.log *.out *.toc
