pdf:
	xelatex neuripsmarg-10min
	biber neuripsmarg-10min
	xelatex neuripsmarg-10min
	xelatex neuripsmarg-10min

fix:
	texliveonfly -c xelatex neuripsmarg-10min

clean:
	rm *.bbl *.nav *.run.xml *.snm *.synctex* *.vrb *.xdv *.aux *.bcf *.blg *.fdb_latexmk *.fls *.log *.out *.toc
