pdf:
	xelatex neuripsmarg-3min
	biber neuripsmarg-3min
	xelatex neuripsmarg-3min
	xelatex neuripsmarg-3min

fix:
	texliveonfly -c xelatex neuripsmarg-3min

clean:
	rm *.bbl *.nav *.run.xml *.snm *.synctex* *.vrb *.xdv *.aux *.bcf *.blg *.fdb_latexmk *.fls *.log *.out *.toc
